/**
 * Cloudflare Pages Edge Function for Dynamic sitemap.xml
 * Proxies dynamic XML sitemap generated by backend API.
 */

export async function onRequest(context) {
  const { env } = context
  try {
    const apiBase = env.VITE_API_BASE_URL || 'https://api.rizaldev.my.id/api/v1'
    const backendOrigin = apiBase.replace(/\/api\/v1\/?$/, '')

    const res = await fetch(`${backendOrigin}/sitemap.xml`, {
      headers: { 'Accept': 'application/xml, text/xml' }
    })

    if (res.ok) {
      const xml = await res.text()
      return new Response(xml, {
        headers: {
          'Content-Type': 'application/xml; charset=UTF-8',
          'Cache-Control': 'public, max-age=300, s-maxage=600'
        }
      })
    }
  } catch (err) {}

  return new Response('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>', {
    headers: {
      'Content-Type': 'application/xml; charset=UTF-8'
    }
  })
}
